name: Go Build Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * 1-6'

jobs:
  build-go:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: hello-server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build for Linux
        run: go build ${{ env.FILE_NAME }}.go

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

      - name: Upload artifact for Linux
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}

      - name: Upload artifact for Windows
        uses: actions/upload-artifact@v1.0.0
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe

download-and-run-linux:
      - name: Download and run Linux
        needs: build-go
      - runs-on: ubuntu-latest
        steps:
        
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: download from artefacts
        uses: actions/download-artifact@v3
        with:
          name: linux
        
      - name: List files in current directory
        run: |
          chmod +x ./run.sh
          source ./run.sh

download-only-windows:
      - name: Download and run windows
        needs: build-go
        runs-on: windows-latest
        steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: download from artefacts
        uses: actions/download-artifact@v3
        with:
          name: windows
